import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export async  function generateTraceabilityReport(row) {



  const doc = new jsPDF();
  doc.addFont('Roboto-Black.ttf', 'Roboto', 'bold');


  doc.setFont('Roboto', 'bold');

  doc.setFontSize(18);
  doc.setFont('Times', 'bold');
  doc.text('Traceability Report', 105, 20, null, null, 'center');

 
  const currentDate = new Date().toLocaleString('en-US', {
    weekday: 'long', 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric', 
    hour: '2-digit', 
    minute: '2-digit', 
    second: '2-digit', 
    hour12: true, 
  });


  const adminData = JSON.parse(localStorage.getItem('admin'));
  const userName = adminData.userName;
  doc.setFontSize(12);


  doc.setFont('Times', 'bold');
  doc.text('Final Product Report:', 20, 40);
  doc.setFont('helvetica', 'normal');
  doc.text(`${row.finishedGoodsName}`, 62, 40); 


  doc.setFont('Times', 'bold');
  doc.text('Finished Product Batch Number:', 20, 50);
  doc.setFont('helvetica', 'normal');
  doc.text(`${row.batchNumber}`, 82, 50); 


  doc.setFont('Times', 'bold');
  doc.text('Date of Report Generation:', 20, 60);
  doc.setFont('helvetica', 'normal');
  doc.text(`${currentDate}`, 72, 60); 

  // Plant Name
  doc.setFont('Times', 'bold');
  doc.text('Plant Name:', 20, 70);
  doc.setFont('helvetica', 'normal');
  doc.text(`${row.plant}`, 45, 70); 

  // Generated By
  doc.setFont('Times', 'bold');
  doc.text('Generated By:', 20, 80);
  doc.setFont('helvetica', 'normal');
  doc.text(`${userName}`, 48, 80); 


  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Raw Materials', 20, 100);
 
  row.materials.map((material,index)=>{
    console.log(material);
  })
  const sanitizedData = row.materials.map((material) => [
    material.materialsList || "N/A",
    material.batchNumber || "N/A",
    String(material.quantity || "0"), // Ensure numbers are converted to strings
    material.vendorId || "N/A",
  ]);

  console.log('sanitize data',sanitizedData);

  doc.autoTable({
    startY: 110,
    head: [['Material Name', 'Batch Number', 'Quantity Used', 'Vendor ID']], 
    body:sanitizedData, 
    theme: 'grid', 
    headStyles: { fillColor: [41, 128, 185] }, 
    margin: { left: 20, right: 20 }, 
  });


  const nextY = doc.lastAutoTable.finalY + 10; 


  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Production Process Details', 20, nextY);
  doc.setFontSize(12);

  doc.setFont('Times', 'bold');
  doc.text('Process Order Number:', 20, nextY + 10);
  doc.setFont('Times', 'normal');
  doc.text(`${row.processOrderNo}`, 65, nextY + 10); 
  
  // Process Description
  doc.setFont('Times', 'bold');
  doc.text('Process Description:', 20, nextY + 20);
  doc.setFont('Times', 'normal');
  doc.text(`${row.description}`, 60, nextY + 20); 


  const plantAssignmentsY = nextY + 40; 

doc.setFontSize(14);
doc.setFont('helvetica', 'bold');
doc.text('Plant Assignments', 20, plantAssignmentsY);


doc.setFontSize(12);
doc.setFont('Times', 'bold');
doc.text('Plant Name:', 20, plantAssignmentsY + 10);
doc.setFont('helvetica', 'normal');
doc.text(`${row.plant}`, 45, plantAssignmentsY + 10);


  const storageDetailsY = plantAssignmentsY + 30; 

doc.setFontSize(14);
doc.setFont('helvetica', 'bold');
doc.text('Storage Details', 20, storageDetailsY);


doc.setFontSize(12);
doc.setFont('Times', 'bold');
doc.text('Storage Location:', 20, storageDetailsY + 10); 
doc.setFont('helvetica', 'normal');
doc.text(`${row.storageLocation}`, 55, storageDetailsY + 10); 


  doc.save('Traceability_Report.pdf');
}


